export {default as getCity} from './app-slice/selectors/get-city/get-city';
export {default as getAppStatus} from './data-slice/selectors/get-app-status/get-app-status';
export {default as getUser} from './user-slice/selectors/get-user/get-user';
export {default as getAuthStatus} from './user-slice/selectors/get-auth-status/get-auth-status';
export {default as getOffers} from './data-slice/selectors/get-offers/get-offers';
export {default as getCurrentOffer} from './data-slice/selectors/get-current-offer/get-current-offer';
export {default as getNearOffers} from './data-slice/selectors/get-near-offers/get-near-offers';
export {default as getReviews} from './data-slice/selectors/get-reviews/get-reviews';
export {default as getFavorites} from './data-slice/selectors/get-favorites/get-favorites';
